/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	qboxv1alpha1 "github.com/xwen-winnie/crd_demo/kube/apis/qbox/v1alpha1"
	versioned "github.com/xwen-winnie/crd_demo/kube/client/clientset/versioned"
	internalinterfaces "github.com/xwen-winnie/crd_demo/kube/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/xwen-winnie/crd_demo/kube/client/listers/qbox/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WaitdeploymentInformer provides access to a shared informer and lister for
// Waitdeployments.
type WaitdeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.WaitdeploymentLister
}

type waitdeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWaitdeploymentInformer constructs a new informer for Waitdeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWaitdeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWaitdeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWaitdeploymentInformer constructs a new informer for Waitdeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWaitdeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QboxV1alpha1().Waitdeployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QboxV1alpha1().Waitdeployments(namespace).Watch(context.TODO(), options)
			},
		},
		&qboxv1alpha1.Waitdeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *waitdeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWaitdeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *waitdeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&qboxv1alpha1.Waitdeployment{}, f.defaultInformer)
}

func (f *waitdeploymentInformer) Lister() v1alpha1.WaitdeploymentLister {
	return v1alpha1.NewWaitdeploymentLister(f.Informer().GetIndexer())
}
